console.log('Hello from Typescript');
var myNum;
var myString;
var myBool;
var myVar;
// let strArr: string[];
// let numArr: number[];
var strArr;
var numArr;
myNum = 2;
myString = 'string';
myBool = false;
myVar = 'true';
strArr = ['hello', 'world'];
numArr = [1, 2];
console.log(myNum);
console.log(myString);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
var strNumTuple;
strNumTuple = ['a', 10];
console.log(strNumTuple);
var myVoid = null;
var myNull = null;
var myUndefined = undefined;
console.log(myVoid);
